# Generated by Django 6.0 on 2025-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('veg', 'Veg'), ('non veg', 'Non-Veg'), ('beverages', 'Beverages')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('Item_name', 'category'), name='unique_menu_item'),
        ),
    ]
