# Generated by Django 6.0 on 2025-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
